### ISSUE TITLE
Stats "sort by" not working

### ISSUE THREAD

**Issue by simonpalmer123** [syncbible/syncbible#12]
When investigating a word, the stats pane is great. I'm sure it used to work, but seems not to now.
What ever I click, on the "Sort by" ("Reference" "Descending" "Ascending") it's only ever sorted by Reference"

**Comment by scruffian** [comment]
Thanks, I'll take a look :)

**Comment by scruffian** [comment]
This was fixed in https://github.com/syncbible/syncbible/commit/2b91e5ed0abbfc58a2c9ec4cf664d8a1599b8e89.
